import sys
path = sys.argv[1]
content = open(path, encoding='utf-8').read()

start = content.index('FALLBACK_TEMPLATES = {')
end = content.index('\n# ─── System Prompt')

new_block = '''FALLBACK_TEMPLATES = {
    "Leave Request": {
        "formal":   "Thank you for submitting your leave request. It has been received by the HR team and is currently under review for scheduling conflicts and policy compliance. While your request is being processed, please take the following steps: (1) Log into the HR portal and verify that your leave balance is sufficient for the requested dates. (2) Notify your direct line manager via email and copy your team so that coverage can be arranged. (3) Ensure any active projects or deadlines are handed over or documented before your leave commences. You will receive a formal approval or query response within one business day.",
        "friendly": "Your leave request has come through — thanks for planning ahead! While we review it, here is what you can do in the meantime: (1) Check your leave balance in the HR portal under My Leave to confirm you have enough days available. (2) Send your manager a quick email letting them know about your planned dates. (3) Start planning any handovers so your team is covered while you are away. We will confirm availability and approval within one business day.",
        "urgent":   "Your leave request has been received and flagged as urgent. The HR team is reviewing it now. In the meantime: (1) Confirm your leave balance in the HR portal immediately. (2) Notify your manager right now — do not wait for HR approval before informing them. (3) Identify who will cover your responsibilities and brief them today. We will respond within 4 hours.",
    },
    "Payslip": {
        "formal":   "We acknowledge receipt of your payslip enquiry and the reported discrepancy is being investigated as a priority. While we investigate, please take the following steps: (1) Log into the HR portal and download your payslip for the affected month to confirm the discrepancy in writing. (2) Cross-reference the gross and net figures against your employment contract or last confirmed salary letter. (3) Note the specific line items that appear incorrect — for example, deductions, allowances, or leave pay — and include these in any follow-up correspondence. A full resolution will be provided within two business days.",
        "friendly": "Thanks for flagging this — payslip issues are always a priority. While the HR team investigates, here is what you can do: (1) Download your payslip from the HR portal and make a note of exactly which figures look wrong. (2) Compare it against your contract or a previous payslip to identify the specific discrepancy. (3) If you have a reference number from payroll or a prior email about a salary change, have that ready — it will speed up the investigation. We will be back to you within two business days.",
        "urgent":   "Your payslip query has been escalated for immediate attention. To help us resolve this as quickly as possible: (1) Download and attach your payslip from the HR portal to this ticket right now. (2) Note the exact figures that are incorrect and what you expected them to be. (3) If this affects a debit order, bond payment, or other financial commitment with a deadline today, state that explicitly in your reply so we can escalate to payroll directly. We will respond within two hours.",
    },
    "HR Policy": {
        "formal":   "Thank you for your policy enquiry. The HR team will retrieve the relevant documentation and respond within one business day. In the meantime, please take the following steps: (1) Check the company intranet or SharePoint HR folder — many policies are published there and may answer your question immediately. (2) Review any onboarding documentation or employment contract clauses that may be relevant to your query. (3) If your query relates to a specific incident or disciplinary matter, document the facts and dates clearly so that HR can advise you accurately. We will follow up with the official policy position shortly.",
        "friendly": "Good question — let us make sure you get the right answer. While HR pulls the relevant documentation, here is what you can try: (1) Check the company intranet or the HR SharePoint folder — the policy you need may already be published there. (2) Have a look through your employment contract for any relevant clauses. (3) If this is about a specific situation, jot down the key facts and dates so HR can give you a precise answer when they respond. We will be back to you within one business day.",
        "urgent":   "Your policy enquiry has been flagged as urgent. While HR sources the documentation: (1) Do not take any action based on assumptions — wait for the official HR position before proceeding. (2) If this relates to a disciplinary, grievance, or legal matter, document everything that has happened so far with dates and names. (3) If another party is pressuring you to act before HR responds, inform them that you are awaiting formal HR guidance. We will respond within four hours.",
    },
    "Password Reset": {
        "formal":   "Your password reset request has been received and is being processed. While you wait for your temporary credential, please attempt the following steps: (1) Check whether your account may be locked rather than expired — three or more failed login attempts typically trigger a lockout that requires IT to unlock it separately from a password reset. (2) Confirm you are using the correct username format, typically firstname.lastname@company.com. (3) If you are attempting to log into a system other than your primary workstation, check whether that system uses a separate set of credentials. Your temporary password will be sent to your registered email within 15 minutes.",
        "friendly": "Password reset is on its way! While you wait, try these steps: (1) Double-check that your username is correct — it is usually firstname.lastname@company.com. (2) If you have been locked out from too many failed attempts, a reset alone may not be enough — IT may also need to unlock the account separately, so mention this in your reply if the reset does not work. (3) Try a different browser or incognito mode when you receive the temporary password, as cached sessions can sometimes interfere with logins. Temporary password incoming within 15 minutes.",
        "urgent":   "Password reset initiated immediately. Steps to follow right now: (1) Check your email inbox and spam folder in exactly five minutes for the temporary credential. (2) When you log in, you will be prompted to set a new password — ensure it meets the complexity requirements: minimum 8 characters, one uppercase letter, one number, one special character. (3) If the reset does not restore access, reply immediately with your employee ID and the exact error message shown — we will escalate to direct IT intervention without delay.",
    },
    "VPN Access": {
        "formal":   "Your VPN connectivity issue has been logged and assigned to the IT Support team. A technician will contact you within two hours. In the meantime, please attempt the following troubleshooting steps: (1) Fully quit your VPN client — do not just minimise it — then reopen and attempt to reconnect. (2) Confirm your internet connection is active by opening a browser and navigating to an external website. (3) Check that your VPN client is on the latest version by navigating to Help or About within the application. (4) If you receive a specific error code, note it down and include it in your reply — this significantly speeds up diagnosis. Do not uninstall the VPN client or restart your machine until the technician has assessed the issue.",
        "friendly": "VPN issue logged and assigned to IT. While you wait for the technician, try these steps: (1) Fully close the VPN client from the system tray and reopen it — a proper restart often clears temporary connection errors. (2) Make sure your internet is working by opening a browser and loading a website. (3) Check if your VPN client needs an update under Help or About — outdated clients are a very common cause of connection failures. (4) Note down the exact error message or code you are seeing and include it in your reply so the technician can diagnose it faster. Someone will reach out within two hours.",
        "urgent":   "Your VPN issue has been escalated as critical. An IT technician will contact you within 30 minutes. Take these steps immediately: (1) Note the exact error code displayed — for example Error 442, Error 619 — and reply with it now so the technician arrives prepared. (2) Try connecting from a mobile hotspot to rule out a local network issue. (3) Check with a colleague whether their VPN is working — if it is a server-side outage, the technician needs to know immediately. (4) Do not uninstall or reinstall the VPN client — this can destroy the configuration and extend your downtime significantly.",
    },
    "Hardware": {
        "formal":   "Your hardware fault has been logged and assigned to the IT Support team. A technician will assess and resolve the issue within one business day. In the meantime, please take the following steps: (1) If your device will still power on, save all open work to a network drive or cloud storage immediately to prevent data loss. (2) Note the make, model, and asset tag of the affected device — this is usually on a sticker on the underside of the laptop or back of the monitor. (3) Document the exact symptoms: what the device does or does not do, any error messages displayed, and when the fault first occurred. If the fault is preventing you from completing critical work, please reply to this ticket with the business impact and we will escalate accordingly.",
        "friendly": "Hardware fault logged with IT. A technician will be in touch within a day. In the meantime: (1) If the device is still partially working, save everything to OneDrive or a network drive now — do not wait. (2) Find the asset tag on the device (usually a sticker on the bottom of the laptop or back of the monitor) and include it in your reply. (3) Write down exactly what is happening: the symptoms, any error messages, and when it started. The more detail you give the technician, the faster they can fix it. If this is completely blocking your work, just say so and we will fast-track it.",
        "urgent":   "Your hardware fault has been escalated as critical. A technician has been dispatched and will attend within one hour. Take these steps now: (1) Save all open work to a network drive or cloud storage immediately — do not wait. (2) If the device has failed completely, check whether you can temporarily use a colleague's machine or a spare device from IT. (3) Note the asset tag, make, and model of the faulty device and reply with it now so the technician brings the correct parts or replacement. (4) Do not attempt to open the device, force a restart repeatedly, or connect it to external power adaptors that were not supplied with it.",
    },
    "Expense Claim": {
        "formal":   "Your expense claim has been received by the Finance team and is currently under review. Standard processing time is three to five business days. While your claim is being reviewed, please verify the following to avoid any delays: (1) Confirm that all receipts are attached as clear, legible images or PDFs — blurry or incomplete receipts are the most common reason for claim delays. (2) Verify that each expense item is assigned to the correct category as per the company expense policy. (3) Ensure that the total amount on each receipt matches the amount entered on the claim form exactly. (4) If your claim includes any foreign currency expenses, confirm that the exchange rate used is consistent with the company-approved rate. Please do not resubmit the claim unless specifically advised to do so.",
        "friendly": "Expense claim received — Finance has it and will process it within three to five business days. While you wait, do a quick check: (1) Make sure all your receipts are attached and are clear enough to read — this is the most common reason claims get delayed or rejected. (2) Double-check that each item is in the right expense category. (3) Confirm that the amounts on your receipts match exactly what you entered on the form. (4) If any items were pre-approved by your manager, make sure that approval is referenced or attached. If everything looks good, sit tight and Finance will process it shortly.",
        "urgent":   "Your expense claim has been flagged as urgent and escalated to Finance for priority review. To help us resolve this as quickly as possible: (1) Reply now with the claim reference number and the specific reason for urgency — for example, a supplier payment deadline or reimbursement needed before travel. (2) Confirm that all receipts are attached and clearly legible. (3) If the claim was previously rejected, include the rejection notification and any reference numbers so Finance can locate it immediately. (4) If manager pre-approval was given verbally, ask your manager to send a written confirmation email so Finance can act on it without delay. We will respond within four hours.",
    },
    "Payroll": {
        "formal":   "Your payroll query has been escalated to the Finance team for immediate investigation and is being treated as a priority matter. To assist with a prompt resolution, please take the following steps: (1) Download your payslip for the affected month from the HR portal and identify the specific line items that are incorrect. (2) Compare the figures against your most recent salary confirmation letter or employment contract. (3) If the discrepancy relates to a salary adjustment, bonus, or commission that was communicated to you, locate the relevant email or letter and attach it to this ticket. (4) If the error affects a debit order or financial commitment with an imminent deadline, state this explicitly so Finance can prioritise accordingly. A full resolution will be provided within one business day.",
        "friendly": "Payroll concern flagged to Finance as a priority — we know how important this is. Here is what you can do while they investigate: (1) Pull up your payslip from the HR portal and note exactly which figures look wrong and what you expected them to be. (2) Compare it against your employment contract or a previous payslip from a month you know was correct. (3) If there was a recent salary change, promotion, or adjustment, find the confirmation email and attach it to this ticket — it will help Finance resolve it much faster. We will be back to you within one business day.",
        "urgent":   "Your payroll discrepancy has been escalated immediately to Finance and is being treated as urgent. Take these steps right now: (1) Download your payslip from the HR portal and screenshot or note the exact figures that are wrong. (2) Reply to this ticket with the specific amounts — what was paid versus what was expected. (3) If this affects a bond, debit order, or payment with a deadline today, state the deadline time explicitly so Finance knows how urgently to act. (4) If a salary adjustment or change was recently communicated to you in writing, attach that confirmation to this ticket immediately. Finance is investigating now and will provide a resolution before end of business today.",
    },
    "Facilities": {
        "formal":   "Your facilities request has been received and assigned to the Operations team for assessment and resolution. The matter will be attended to within two business days. In the meantime, please take the following steps: (1) Determine whether the issue poses an immediate safety risk — if it does, contact reception or building security immediately and do not wait for this ticket to be resolved. (2) Use your phone to photograph or video the issue clearly, including any visible damage, affected equipment, or environmental conditions such as temperature or flooding. (3) Note the exact room number, floor, and asset tag or equipment label so the technician can locate the fault immediately upon arrival. (4) Identify whether the issue is isolated to your workstation or affecting a wider area, and document which colleagues are impacted.",
        "friendly": "Facilities request logged and with the Operations team. They will get on it within two business days. While you wait: (1) If there is any safety risk involved — electrical, structural, or health-related — contact reception or building security right now, do not wait for this ticket. (2) Take a photo or short video of the issue on your phone so the technician knows exactly what to expect when they arrive. (3) Note the room number and any asset tag or label on the affected equipment. (4) Check if colleagues nearby are experiencing the same issue — if it is widespread, let us know so we can escalate the priority.",
        "urgent":   "Your facilities issue has been escalated as urgent. The Operations team will attend within two hours. Take these steps immediately: (1) If the issue poses a health or safety risk — gas leak, electrical fault, flooding, extreme temperature — evacuate the affected area now and contact building security or reception directly without waiting for this ticket response. (2) Photograph or video the issue right now and attach it to this ticket so the technician arrives fully briefed. (3) Note the exact room number and asset tag of the affected equipment and reply with it immediately. (4) If the issue is affecting multiple people or an entire floor, notify your floor manager directly so they can coordinate a temporary workaround while the repair is in progress.",
    },
    "Office Supplies": {
        "formal":   "Your office supplies request has been received and is being processed by the Operations team. Items will be sourced and delivered to your designated workspace within two business days, subject to stock availability. To ensure your request is fulfilled accurately and without delay: (1) Confirm that the items requested are on the approved supplies list — requests for non-standard items may require manager sign-off. (2) Ensure your desk or delivery location is clearly specified in the ticket. (3) If any items are required for a specific meeting, event, or deadline, state the date explicitly so the Operations team can prioritise delivery accordingly.",
        "friendly": "Supplies request received and with the Operations team. Delivery within two business days. A couple of things to check: (1) Make sure the items you need are on the standard approved supplies list — if they are not, you may need a quick manager sign-off first. (2) Let us know your exact desk location or delivery point if it is not already on file. (3) If you need these items by a specific date for a meeting or presentation, mention that date in your reply so we can make sure delivery happens in time.",
        "urgent":   "Urgent supplies request received and flagged for same-day processing. To make sure we can fulfil this today: (1) Reply immediately with the exact items needed, quantities, and the deadline time — for example needed by 2pm for client meeting. (2) Confirm your desk location or the delivery point where items should be dropped. (3) If any items are non-standard or not on the approved list, get manager approval right now and copy them on your reply so Operations can proceed without delay. The team is checking stock levels now.",
    },
    "General Support": {
        "formal":   "Thank you for contacting the support team. Your request has been received, logged, and assigned to the appropriate department for resolution. While your ticket is being reviewed, please take the following steps to assist with a faster resolution: (1) Ensure your ticket includes a clear description of the issue, when it started, and what you have already tried. (2) If the issue relates to a specific system, application, or piece of equipment, include the name, version number, or asset tag where possible. (3) If the issue is intermittent, note the exact times and conditions under which it occurs. (4) Do not submit duplicate tickets for the same issue as this may delay resolution. You can expect an initial response within one business day.",
        "friendly": "Thanks for reaching out — your request is logged and with the right team. To help us resolve it as quickly as possible: (1) Make sure your ticket description is as detailed as possible — what the issue is, when it started, and what you have already tried. (2) If it involves a system or application, include the name and version if you know it. (3) If the issue comes and goes, note when it happens and under what conditions. (4) Do not submit the same ticket twice — it can slow things down rather than speed them up. We will be in touch within one business day.",
        "urgent":   "Your request has been received and escalated for urgent attention. The relevant team is reviewing it now. To help us act as quickly as possible: (1) Reply immediately with a clear description of the business impact — for example, how many people are affected, what work is blocked, and whether there is a financial or client-facing deadline involved. (2) Include any error messages, reference numbers, or system names relevant to the issue. (3) If you have already tried any troubleshooting steps, list them so the team does not repeat them and wastes your time. (4) If the situation escalates further before we respond, contact your line manager so they are aware of the impact.",
    },
}

'''

content = content[:start] + new_block + content[end:]
open(path, 'w', encoding='utf-8').write(content)
print('[OK] Detailed troubleshooting templates applied successfully')
